### ISSUE TITLE
兄弟チャンネル作ってるとたまにレイアウト崩れてるのが出現する

### ISSUE THREAD

**Issue by annin3** [hackathon-21winter-05/HiQidas_UI#26]
borderとか矢印が不透明度0になってるっぽい

![image](https://user-images.githubusercontent.com/63178126/145572570-9d1a237c-9fc8-4908-80d0-784d30d76a37.png)

**Comment by reyu0722** [comment]
エスパーなんですがランダムで色を生成している部分がバグってる気がします
で、今 `heya` ブランチでは事前に決めた色の中から選ぶようにしてるので、直ってる気がします (どっちも未検証)
